identifier = "com.luxonis.customfrontend.dynamicyoloworld"
entrypoint = ["bash", "-c", "/usr/bin/runsvdir -P /etc/service"]
app_version = "1.0.1"

prepare_container = [
    { type = "COPY", source = "./backend/src/requirements.txt", target = "./backend/src/requirements.txt" },
    { type = "RUN", command = "python3.12 -m pip install -r /app/backend/src/requirements.txt --break-system-packages"}
]

build_steps = [
    "mkdir -p /etc/service/backend",
    "cp /app/backend-run.sh /etc/service/backend/run",
    "chmod +x /etc/service/backend/run",
]

[static_frontend]
dist_path = "./frontend/dist"

[static_frontend.build]
source_path = "./frontend"
steps = ["bash -c 'echo \"Frontend has to be prebuild before building the container\"'"]

[base_image]
api_url = "https://registry-1.docker.io"
service = "registry.docker.io"
oauth_url = "https://auth.docker.io/token"
auth_type = "repository"
auth_name = "luxonis/oakapp-base"
image_name = "luxonis/oakapp-base"
image_tag = "1.2.4"